// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkforceManager.Data;

#nullable disable

namespace WorkforceManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903162037_RemoveInitialBalanceReason")]
    partial class RemoveInitialBalanceReason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("WorkforceManager.Core.Models.ActivityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("ActivityEvents");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenActivityLogAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("WorkerId")
                        .IsUnique()
                        .HasFilter("\"WorkerId\" IS NOT NULL");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("WorkerId", "Date")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.DailyProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBalanceCompletion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRework")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PieceCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PiecesPerWorkdayAtEntry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductionStageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("WorkerId", "ProductionStageId", "Date");

                    b.HasIndex("ProductionStageId", "Date", "IsDeleted", "PieceCount", "IsRework", "IsBalanceCompletion");

                    b.ToTable("DailyProductions", t =>
                        {
                            t.HasCheckConstraint("CK_DailyProduction_Amounts", "[PieceCount] >= 0 AND [PiecesPerWorkdayAtEntry] > 0");
                        });
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.HourlyWorkLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndHour24")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WorkdaysCredited")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("WorkerId", "Date")
                        .IsUnique();

                    b.ToTable("HourlyWorkLogs");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.InitialBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginalDailyProductionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OriginalDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OriginalDailyProductionId");

                    b.HasIndex("ProductId", "OriginalDate");

                    b.ToTable("InitialBalances", t =>
                        {
                            t.HasCheckConstraint("CK_InitialBalance_Quantity", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.InitialBalanceRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromStageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialBalanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PieceCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToStageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromStageId");

                    b.HasIndex("InitialBalanceId");

                    b.HasIndex("ToStageId");

                    b.ToTable("InitialBalanceRanges", t =>
                        {
                            t.HasCheckConstraint("CK_InitialBalanceRange_PieceCount", "[PieceCount] > 0");
                        });
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.InitialBalanceUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DailyProductionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialBalanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InitialBalanceRangeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductionScrapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductionStageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UsedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DailyProductionId")
                        .IsUnique();

                    b.HasIndex("InitialBalanceId");

                    b.HasIndex("InitialBalanceRangeId");

                    b.HasIndex("ProductionScrapId")
                        .IsUnique();

                    b.HasIndex("ProductionStageId");

                    b.HasIndex("WorkerId");

                    b.ToTable("InitialBalanceUsages", t =>
                        {
                            t.HasCheckConstraint("CK_InitialBalanceUsage_Quantity", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.OperationsCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique()
                        .HasFilter("\"AppUserId\" IS NOT NULL");

                    b.ToTable("OperationsCredentials");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.Penalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Deduction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("WorkerId", "Date");

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RackingWorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RackingWorkerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.ProductionDayClosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedPieces")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartedPieces")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("ProductionDayClosures");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.ProductionScrap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("PieceCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductionStageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScrapReasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("ScrapReasonId");

                    b.HasIndex("ProductionStageId", "Date", "PieceCount");

                    b.ToTable("ProductionScraps");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.ProductionStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DifficultyMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(1.0m);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRackingStage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PiecesPerWorkday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductionStages", t =>
                        {
                            t.HasCheckConstraint("CK_ProductionStage_Difficulty", "[DifficultyMultiplier] > 0");

                            t.HasCheckConstraint("CK_ProductionStage_Quota", "[PiecesPerWorkday] > 0");
                        });
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.ProductionStageOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("PieceCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductionStageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("ProductionStageId", "Date")
                        .IsUnique();

                    b.HasIndex("ProductionStageId", "Date", "PieceCount");

                    b.ToTable("ProductionStageOutputs");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.ScrapReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ScrapReasons");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.WageAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountEgp")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("WorkerId", "Date");

                    b.ToTable("WageAdjustments", t =>
                        {
                            t.HasCheckConstraint("CK_WageAdjustment_Amount", "[AmountEgp] > 0");
                        });
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DailyWageEgp")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HourlyRole")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PhotoData")
                        .HasColumnType("BLOB");

                    b.Property<string>("SkillsNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.ToTable("Workers", t =>
                        {
                            t.HasCheckConstraint("CK_Worker_DailyWage", "[DailyWageEgp] >= 0");
                        });
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.WorkerPerformanceTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("TitleType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.HasIndex("TitleType", "PeriodStart");

                    b.ToTable("WorkerPerformanceTitles");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.WorkerSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MeasuredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MeasuredDays")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MeasuredRatio")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ProductionStageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StarsUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StarsUpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductionStageId");

                    b.HasIndex("WorkerId", "ProductionStageId")
                        .IsUnique();

                    b.ToTable("WorkerSkills", t =>
                        {
                            t.HasCheckConstraint("CK_WorkerSkill_Stars", "[Stars] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.AppUser", b =>
                {
                    b.HasOne("WorkforceManager.Core.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.Attendance", b =>
                {
                    b.HasOne("WorkforceManager.Core.Models.Worker", "Worker")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.DailyProduction", b =>
                {
                    b.HasOne("WorkforceManager.Core.Models.ProductionStage", "ProductionStage")
                        .WithMany("ProductionRecords")
                        .HasForeignKey("ProductionStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkforceManager.Core.Models.Worker", "Worker")
                        .WithMany("ProductionRecords")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionStage");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.HourlyWorkLog", b =>
                {
                    b.HasOne("WorkforceManager.Core.Models.Worker", "Worker")
                        .WithMany("HourlyWorkLogs")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.InitialBalance", b =>
                {
                    b.HasOne("WorkforceManager.Core.Models.DailyProduction", "OriginalDailyProduction")
                        .WithMany()
                        .HasForeignKey("OriginalDailyProductionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WorkforceManager.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OriginalDailyProduction");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.InitialBalanceRange", b =>
                {
                    b.HasOne("WorkforceManager.Core.Models.ProductionStage", "FromStage")
                        .WithMany()
                        .HasForeignKey("FromStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkforceManager.Core.Models.InitialBalance", "InitialBalance")
                        .WithMany("Ranges")
                        .HasForeignKey("InitialBalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkforceManager.Core.Models.ProductionStage", "ToStage")
                        .WithMany()
                        .HasForeignKey("ToStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStage");

                    b.Navigation("InitialBalance");

                    b.Navigation("ToStage");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.InitialBalanceUsage", b =>
                {
                    b.HasOne("WorkforceManager.Core.Models.DailyProduction", "DailyProduction")
                        .WithMany()
                        .HasForeignKey("DailyProductionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkforceManager.Core.Models.InitialBalance", "InitialBalance")
                        .WithMany("Usages")
                        .HasForeignKey("InitialBalanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkforceManager.Core.Models.InitialBalanceRange", "Range")
                        .WithMany()
                        .HasForeignKey("InitialBalanceRangeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WorkforceManager.Core.Models.ProductionScrap", "ProductionScrap")
                        .WithMany()
                        .HasForeignKey("ProductionScrapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkforceManager.Core.Models.ProductionStage", "ProductionStage")
                        .WithMany()
                        .HasForeignKey("ProductionStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkforceManager.Core.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DailyProduction");

                    b.Navigation("InitialBalance");

                    b.Navigation("ProductionScrap");

                    b.Navigation("ProductionStage");

                    b.Navigation("Range");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.OperationsCredential", b =>
                {
                    b.HasOne("WorkforceManager.Core.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.Penalty", b =>
                {
                    b.HasOne("WorkforceManager.Core.Models.Worker", "Worker")
                        .WithMany("Penalties")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.Product", b =>
                {
                    b.HasOne("WorkforceManager.Core.Models.Worker", "RackingWorker")
                        .WithMany()
                        .HasForeignKey("RackingWorkerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RackingWorker");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.ProductionScrap", b =>
                {
                    b.HasOne("WorkforceManager.Core.Models.ProductionStage", "ProductionStage")
                        .WithMany()
                        .HasForeignKey("ProductionStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkforceManager.Core.Models.ScrapReason", "Reason")
                        .WithMany("ScrapRecords")
                        .HasForeignKey("ScrapReasonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProductionStage");

                    b.Navigation("Reason");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.ProductionStage", b =>
                {
                    b.HasOne("WorkforceManager.Core.Models.Product", "Product")
                        .WithMany("Stages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.ProductionStageOutput", b =>
                {
                    b.HasOne("WorkforceManager.Core.Models.ProductionStage", "ProductionStage")
                        .WithMany()
                        .HasForeignKey("ProductionStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionStage");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.WageAdjustment", b =>
                {
                    b.HasOne("WorkforceManager.Core.Models.Worker", "Worker")
                        .WithMany("WageAdjustments")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.WorkerPerformanceTitle", b =>
                {
                    b.HasOne("WorkforceManager.Core.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.WorkerSkill", b =>
                {
                    b.HasOne("WorkforceManager.Core.Models.ProductionStage", "ProductionStage")
                        .WithMany("QualifiedWorkers")
                        .HasForeignKey("ProductionStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkforceManager.Core.Models.Worker", "Worker")
                        .WithMany("Skills")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionStage");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.InitialBalance", b =>
                {
                    b.Navigation("Ranges");

                    b.Navigation("Usages");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.Product", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.ProductionStage", b =>
                {
                    b.Navigation("ProductionRecords");

                    b.Navigation("QualifiedWorkers");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.ScrapReason", b =>
                {
                    b.Navigation("ScrapRecords");
                });

            modelBuilder.Entity("WorkforceManager.Core.Models.Worker", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("HourlyWorkLogs");

                    b.Navigation("Penalties");

                    b.Navigation("ProductionRecords");

                    b.Navigation("Skills");

                    b.Navigation("WageAdjustments");
                });
#pragma warning restore 612, 618
        }
    }
}
