using WorkforceManager.Core.Enums;
using WorkforceManager.Core.Interfaces;
using WorkforceManager.Core.Models;

namespace WorkforceManager.Business.Services
{
    /// <summary>
    /// مسؤولة عن تسجيل وإدارة الجزاءات: جزاء بسبب معين (شرب سجاير،
    /// لبس هاندفري أثناء الشغل، ...) وخصم محدد (نص يوم / يوم / 3 أيام /
    /// أسبوع). الجزاء مستقل عن الحضور — بيتسجل لعامل حاضر أو غايب عادي —
    /// وأثره الحسابي (الخصم من يوميات الأسبوع) بيتطبق في WeeklySummaryService.
    /// </summary>
    public class PenaltyService
    {
        private readonly IPenaltyRepository _penaltyRepo;
        private readonly OperationsPasswordService _gate;

        public PenaltyService(IPenaltyRepository penaltyRepo, OperationsPasswordService gate)
        {
            _penaltyRepo = penaltyRepo;
            _gate = gate;
        }

        /// <summary>
        /// يسجل جزاء جديد على عامل في تاريخ معين بسبب وخصم محددين.
        /// ده المسار الوحيد لإنشاء أي جزاء — سواء المستخدم كتبه بإيده أو
        /// النظام ولّده تلقائيًا (بيفرّق بينهم بـ <paramref name="source"/>).
        /// </summary>
        /// <param name="source">
        /// مصدر الجزاء. الافتراضي "يدوي" فكل النداءات القديمة شغالة زي ما هي.
        /// </param>
        /// <param name="saveChanges">
        /// اعمل حفظ فورًا؟ بيتحط false لما الجزاء يكون جزء من عملية أكبر
        /// (زي حفظ الحضور) عشان كل حاجة تتحفظ في معاملة واحدة.
        /// </param>
        /// <param name="operationsPassword">
        /// كلمة سر العمليات — مطلوبة للجزاءات **اليدوية** بس. الجزاء
        /// التلقائي بيتولّد جوه حفظ الحضور اللي عدّى على البوابة خلاص،
        /// وطلبها تاني كان هيبقى سؤالين على نفس العملية.
        /// </param>
        public async Task<Penalty> RecordPenaltyAsync(
            int workerId, DateTime date, string reason, PenaltyDeduction deduction,
            PenaltySource source = PenaltySource.Manual,
            bool saveChanges = true,
            string operationsPassword = "")
        {
            if (string.IsNullOrWhiteSpace(reason))
                throw new ArgumentException("سبب الجزاء مطلوب", nameof(reason));

            if (source == PenaltySource.Manual) await EnsureAllowedAsync(operationsPassword);

            var penalty = new Penalty
            {
                WorkerId = workerId,
                Date = date.Date,
                Reason = reason.Trim(),
                Deduction = deduction,
                Source = source
            };

            await _penaltyRepo.AddAsync(penalty);
            if (saveChanges) await _penaltyRepo.SaveChangesAsync();
            return penalty;
        }

        /// <summary>
        /// يعدّل جزاء يدوي متسجّل (السبب و/أو الخصم و/أو الملاحظة).
        ///
        /// **الجزاءات التلقائية مش بتتعدّل من هنا** ولنفس سبب منع حذفها:
        /// هي انعكاس لحالة الحضور، فلو المستخدم عدّل خصمها، أول حفظ
        /// للحضور هيصالحها ويرجّعها لنص يومية — تعديل بيختفي لوحده أسوأ
        /// من تعديل ممنوع. و<c>Source</c> مبيتغيّرش أبدًا هنا: الجزاء
        /// اليدوي بيفضل يدوي، فالتفرقة في سجل المراجعة بتفضل صحيحة.
        /// </summary>
        public async Task<Penalty> UpdatePenaltyAsync(
            int penaltyId, string reason, PenaltyDeduction deduction,
            string operationsPassword = "")
        {
            if (string.IsNullOrWhiteSpace(reason))
                throw new ArgumentException("سبب الجزاء مطلوب", nameof(reason));

            var penalty = await _penaltyRepo.GetByIdAsync(penaltyId)
                ?? throw new InvalidOperationException("الجزاء المحدد غير موجود");

            if (penalty.IsAutoGenerated)
                throw new InvalidOperationException(
                    "ده جزاء تلقائي بسبب غياب بدون إذن — مش بيتعدّل بالإيد. " +
                    "غيّر حالة حضور العامل من تبويب \"الحضور والغياب\" وهو هيتظبط لوحده.");

            await EnsureAllowedAsync(operationsPassword);

            penalty.Reason = reason.Trim();
            penalty.Deduction = deduction;

            _penaltyRepo.Update(penalty);
            await _penaltyRepo.SaveChangesAsync();
            return penalty;
        }

        /// <summary>
        /// بوابة كلمة السر — نداء واحد في مكان واحد بدل ما كل دالة
        /// تكرر نفس السطرين.
        /// </summary>
        private async Task EnsureAllowedAsync(string operationsPassword)
        {
            var gate = await _gate.VerifyAsync(SensitiveAction.SavePenalty, operationsPassword);
            if (!gate.IsAllowed) throw new InvalidOperationException(gate.Message);
        }

        /// <summary>
        /// يحذف جزاء مسجّل بالخطأ (حذف فعلي، مش Soft Delete، لأن الجزاء الغلط مالوش قيمة تاريخية).
        /// الجزاءات التلقائية مش بتتشال من هنا — دي بتتولّد وبتتشال لوحدها
        /// مع حالة الحضور، فحذفها يدوي هيرجّعها تاني أول حفظ للحضور.
        /// </summary>
        public async Task RemovePenaltyAsync(int penaltyId)
        {
            var penalty = await _penaltyRepo.GetByIdAsync(penaltyId)
                ?? throw new InvalidOperationException("الجزاء المحدد غير موجود");

            if (penalty.IsAutoGenerated)
                throw new InvalidOperationException(
                    "ده جزاء تلقائي بسبب غياب بدون إذن — بيتشال لوحده لما تغيّر حالة حضور العامل " +
                    "من تبويب \"الحضور والغياب\".");

            _penaltyRepo.Remove(penalty);
            await _penaltyRepo.SaveChangesAsync();
        }

        /// <summary>كل جزاءات يوم معين لكل العمال (لعرضها في شاشة التسجيل اليومي)</summary>
        public Task<IReadOnlyList<Penalty>> GetPenaltiesByDateAsync(DateTime date)
            => _penaltyRepo.GetByRangeAsync(date, date);
    }
}
